// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"cicd.robot/robot/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/robot/api/callback",
				Handler: RobotHandler(serverCtx),
			},
		},
	)
}
