// Code generated by goctl. DO NOT EDIT.
package types

type FlyPigeonRequest struct {
	MsgType     string `json:"msgType"`
	ChatType    string `json:"chatType"`
	MsgContent  string `json:"msgContent"`
	ChatID      string `json:"chatId"`
	BotKey      string `json:"botKey"`
	HookURL     string `json:"hookUrl"`
	BotName     string `json:"botName"`
	UserName    string `json:"userName"`
	MsgID       string `json:"msgId"`
	ChatInfoURL string `json:"chatInfoUrl"`
	ResponseURL string `json:"responseUrl"`
}

type Response struct {
	Message string `json:"message"`
}
